name: Infrastructure Deploy

on:
  workflow_dispatch:
env:
  TF_VAR_prefix: "project"
  TF_VAR_location: "Poland Central"
permissions:
      id-token: write
      contents: read

jobs:
  deploy-infra:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config=resource_group_name="${{ env.TF_VAR_prefix }}-st-rg" \
            -backend-config=storage_account_name="${{ env.TF_VAR_prefix }}st" \
            -backend-config=container_name="tfstate" \
            -backend-config=key="infra.tfstate"

      - name: Terraform Plan
        run: |
          terraform plan \
            -var="subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}" \
            -var="prefix=${{ env.TF_VAR_prefix }}" \
            -var="location=${{ env.TF_VAR_location }}" \
            -out=tfplan


      - name: Terraform Apply
        run: |
          terraform apply \
          -var="subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}" \
          -var="prefix=${{ env.TF_VAR_prefix }}" \
          -var="location=${{ env.TF_VAR_location }}" \
          -auto-approve tfplan

      